### ISSUE TITLE
Subtract a DirectoryPath from a FilePath (or DirectoryPath)

### ISSUE THREAD

**Issue by HowardvanRooijen** [spectresystems/spectre.io#6]
I have an absolute `FilePath`:

```csharp
FilePath indexFilePath= new(@"C:/site/theme/views/services/index.cshtml");
```
and an absolute `DirectoryPath`:

```csharp
DirectoryPath themeDirectoryPath = new(@"C:/site/theme/views");
```

I would like to be able to subtract the `themeDirectoryPath` from `indexFilePath` so that I end up with a new "rebased" or relative (I'm not entirely sure what the right term is???)

To achieve this currently I can do:

```csharp
var rebased = themeDirectoryPath.GetRelativePath(indexFilePath);
```

Where `rebased` = `services/index.cshtml`

But to my mind, this seems the wrong way around and feels like it should be a method on `FilePath`

I could be thinking about it entirely the wrong way, but it was just a UX thing for me.

Also, I was wondering why it ends up as `services/index.cshtml` rather than `/services/index.html`

**Comment by patriksvensson** [comment]
Will think about what the best approach forward is.

> Also, I was wondering why it ends up as services/index.cshtml rather than /services/index.html

Because `/services/index.html` is a rooted, absolute path.

**Comment by patriksvensson** [comment]
Relative paths are harder than they look.

```csharp
using Spectre.IO;

DirectoryPath a = "C:/site/theme/views";
DirectoryPath b = "C:/site/theme/views/services";
FilePath c = "C:/site/theme/views/services/index.cshtml";

Console.WriteLine($"a(b) => {a.GetRelativePath(b)}");
Console.WriteLine($"a(c) => {a.GetRelativePath(c)}");
Console.WriteLine($"b(c) => {b.GetRelativePath(c)}");
Console.WriteLine($"b(a) => {b.GetRelativePath(a)}");
Console.WriteLine($"c(a) => {c.GetRelativePath(a)}");
Console.WriteLine($"c(b) => {c.GetRelativePath(b)}");
```

The output of that program would be:

```
a(b) => services
a(c) => services/index.cshtml
b(c) => index.cshtml
b(a) => ..
c(a) => ..
c(b) => .
```

An example of what I'm trying to say:

If you consider `a(b)`, that would mean "give me the relative path from a to b", i.e. the relative path from `C:/site/theme/views` to `C:/site/theme/views/services`, which is `./services`.

```shell
C:/site/theme/views> cd services
C:/site/theme/views/services>
```

However, if you turn it around and get the relative path from `b` to `a`, i.e., the relative path from `C:/site/theme/views/services` to `C:/site/theme/views`, that will resolve to `..`.

```
C:/site/theme/views/services> cd ..
C:/site/theme/views>
```

So although it might feel wrong, it's actually correct in the implementation.
